version: '3.9'

services:
    http:
        privileged: true
        container_name : res_http
        hostname: res.http
        build: docker-images/apache-php-image/
        networks:
            lan:
                ipv4_address: 173.17.0.2

    express:
        privileged: true
        container_name : res_express
        hostname : res.express
        build: express-image/
        networks:
            lan:
                ipv4_address: 173.17.0.3

    reverse-proxy:
        privileged: true
        container_name : res_proxy
        hostname : res.proxy
        build: apache-reverse-proxy/
        networks:
            lan:
                ipv4_address: 173.17.0.4   
        environment: 
            - STATIC_APP=173.17.0.2:80
            - DYNAMIC_APP=173.17.0.3:3000 
 
networks:
  lan:
    driver: bridge
    ipam:
      config:    
        - subnet: 173.17.0.0/24
