version: '3.9'

services:
    http:
        privileged: true
        container_name : res_http
        hostname: res.http
        build: docker-images/apache-php-image/
        networks:
            default:
                ipv4_address: 172.18.0.2

    express:
        privileged: true
        container_name : res_express
        hostname : res.express
        build: express-image/
        networks:
            default:
                ipv4_address: 172.18.0.3

    reverse-proxy:
        privileged: true
        container_name : res_proxy
        hostname : res.proxy
        build: apache-reverse-proxy/
        networks:
            default:
                ipv4_address: 172.18.0.4   
        environment: 
            - STATIC_APP=172.18.0.2:80
            - DYNAMIC_APP=172.18.0.3:3000

# docker-compose up --detach   
